### ISSUE TITLE
Can't run at 60fps with my own compiled version

### ISSUE THREAD

**Issue by Morphlng** [davidtranhq/Qtboy#13]
## Problem

This is an interesting project and I want to study the source code further, so I download it and setup the environment. I've met a problem so far that my **own compiled version can only run at 45fps**, however the release version is running at full 60fps.

Own compiled version:
<img width="240" alt="own_compiled" src="https://user-images.githubusercontent.com/50166287/131055212-6b218bc3-62b0-4f10-abd8-0df7c98c11eb.png">

Release version:
<img width="240" alt="Release_version" src="https://user-images.githubusercontent.com/50166287/131055249-66fb9cb3-6b28-4348-a14b-ff4eff084365.png">

I'm not sure what's wrong, maybe qt version issue?

## Environment

1. Win10 + SDL2-devel-2.0.16-mingw
2. Qt 5.15.2 Mingw 64-bit

**Comment by davidtranhq** [comment]
Hey @Morphlng, you're right that is weird. Even without the optimizations from the release build, that is a pretty big performance drop. I wonder if any changes from Qt 5.13 to Qt 5.15 cause this? I'm skeptical it would since it's unlikely that an update would affect performance to this degree, but it is possible.

Perhaps try compiling with Qt 5.13 and seeing if it makes a difference?
